user: "{{ mailtrain_user }}"
group: "{{ mailtrain_group }}"
roUser: nobody
roGroup: nobody

www:
  host: 127.0.0.1
  publicPort: {{ mailtrain_endpoint_public_port }}
  trustedPort: {{ mailtrain_endpoint_trusted_port }}
  sandboxPort: {{ mailtrain_endpoint_sandbox_port }}
  proxy: false
  secret: "{{ mailtrain_secret }}"
  publicUrlBase: "https://{{ mailtrain_endpoint_public }}"
  trustedUrlBase: "https://{{ mailtrain_endpoint_trusted }}"
  sandboxUrlBase: "https://{{ mailtrain_endpoint_sandbox }}"

mysql:
  database: "{{ mailtrain_database_name }}"
  user: "{{ mailtrain_database_user }}"
  password: "{{ mailtrain_database_password }}"

redis:
  enabled: true

log:
  level: info

builtinZoneMTA:
  enabled: false

queue:
  # How many parallel sender processes to spawn
  processes: 5

  # For how long (in seconds) to try to send an email before Mailtrain stops to trying. An email can normally
  # be sent out almost immediately. However if the send configuration is not correct or the mail server is not reachable,
  # Mailtrain will keep retrying until the email expires.
  # Due to Mailtrain's internal timeouts, the values should be at least 60 seconds.
  retention:
    # Regular and RSS campaign. Once this expires, the campaign is considered finished. The remaining recipients
    # are included in the set of those recipients to whom the message would be delivered if the campaign is again started.
    campaign: 86400    # 1 day
    # Triggered campaign. Once this expires, the message gets discarded.
    triggered: 86400   # 1 day
    # Test send (in campaign or template)
    test: 300          # 5 minutes
    # Subscription and password reset related emails
    subscription: 300  # 5 minutes
    # Transactional emails sent via API (i.e. /templates/:templateId/send)
    apiTransactional: 3600  # 60 minutes

ldap:
  enabled: false
