# https://github.com/Mailtrain-org/mailtrain

- name: install dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      # for ansible mysql task
      - python3-pymysql

      # for mailtrain itself
      - mariadb-server
      - imagemagick
      - redis-server

- name: add mailtrain user
  user:
    name: "{{ mailtrain_user }}"

- name: add mailtrain group
  group:
    name: "{{ mailtrain_group }}"

- import_tasks: database.yml

- import_tasks: mailtrain.yml

- import_tasks: nginx.yml

- import_tasks: cert.yml

- import_tasks: services.yml