---
# configures attached data volumes
#
# required vars:
#   - base__volumes__trustroots_data__device

- name: install dependencies
  apt:
    name:
      - cryptsetup
      - lvm2
      - xfsprogs

- name: setup luks device
  luks_device:
    device: "{{ base__volumes__trustroots_data__device }}"
    name: trustroots-data
    state: opened
    keyfile: /root/trustroots-data-keyfile

- name: setup crypttab
  crypttab:
    backing_device: "{{ base__volumes__trustroots_data__device }}"
    name: trustroots-data
    state: present
    password: /root/trustroots-data-keyfile

- name: create volume group
  lvg:
    vg: trustroots-data
    pvs: /dev/mapper/trustroots-data

- name: create mongodb logical volume
  lvol:
    vg: trustroots-data
    lv: mongodb
    size: 60g

- name: create mongodb filesystem
  filesystem:
    dev: /dev/trustroots-data/mongodb
    fstype: xfs

- name: mount mongodb filesystem
  mount:
    src: /dev/trustroots-data/mongodb
    path: /volumes/trustroots-data/mongodb
    fstype: xfs
    # options recommended by DigitalOcean in "Configure your volume"
    opts: discard,defaults,noatime
    state: present